name: Deploy flask App to Google Cloud Run
on: 
  push:
    branches:
      -  main
env: 
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  deploy:
    name: Deploy to cloud run
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{github.sha}}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with: 
          token_format: 'access_token'
          workload_identity_provider: ${{secrets.WORKLOAD_IDENTITY_PROVIDER}}
          service_account: ${{secrets.SERVICE_ACCOUNT}}

      #  Build and push image to artifact registry
      - name: Build
        run: gcloud builds submit --region=us-west2 --tag us-west2-docker.pkg.dev/$PROJECT_ID/my-second-cloud-run-repo/flask-image-testing:$IMAGE_TAG

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: my-flask-app
          region: 'us-west2'
          image:   us-west2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-second-cloud-run-repo/flask-image-testing:${{github.sha}}